apiVersion: v1
kind: Service
metadata:
  name: easyshop-service
  namespace: easyshop
spec:
  type: LoadBalancer  # Change from NodePort to LoadBalancer
  ports:
    - port: 80        # Access via standard Port 80
      targetPort: 3000
  selector:
    app: easyshop